name: civicapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^10.1.0
  video_player: ^2.9.1
  path_provider: ^2.1.4
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - web/icons/Icon-192.png
    - assets/images/
    - assets/images/pole image.webp
    - assets/images/water leak image.jpeg
    - assets/images/2ndroadimadge.jpg
